sudo: false

language: python

python:
  - 2.7

install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install -r requirements.pip && pip install codecov

script:
  - coverage run tests/start_test.py

after_success:
  - codecov
